[tool.poetry]
name = "hbv"
version = "0.1.0"
description = ""
authors = ["Kaiming <mads396@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
biopython = "^1.83"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
